In [1]:
import sys

print("Python executable:")
print(sys.executable)

print("\nPython version:")
print(sys.version)

Python executable:
c:\Users\KIIT\clickbait-credibility-system\.venv\Scripts\python.exe

Python version:
3.12.12 (main, Dec  9 2025, 19:02:55) [MSC v.1944 64 bit (AMD64)]

In [2]:
import pandas as pd
import numpy as np
import sklearn
import matplotlib
import seaborn as sns
import joblib

print("pandas:", pd.__version__)
print("numpy:", np.__version__)
print("scikit-learn:", sklearn.__version__)
print("matplotlib:", matplotlib.__version__)
print("seaborn:", sns.__version__)
print("joblib:", joblib.__version__)

print("\nNOTEBOOK ENVIRONMENT OK")

pandas: 3.0.6
numpy: 2.5.3
scikit-learn: 1.9.1
matplotlib: 3.11.2
seaborn: 0.13.2
joblib: 1.6.0

NOTEBOOK ENVIRONMENT OK

In [4]:
from pathlib import Path

# The notebook is inside /notebooks, so go one level up.
project_root = Path.cwd().parent

print("Project root:")
print(project_root)

print("\nClickbait raw files:")
clickbait_raw = project_root / "data" / "raw" / "clickbait"

for path in clickbait_raw.rglob("*"):
    if path.is_file():
        print(path)

print("\nProcessed files:")
processed = project_root / "data" / "processed"

for path in processed.rglob("*"):
    if path.is_file():
        print(path)

Project root:
c:\Users\KIIT\clickbait-credibility-system

Clickbait raw files:
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\clickbait17-train-170630.zip
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\instances.jsonl
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\truth.jsonl
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804083561460428801.png
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804088734731812865.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804119509338640385.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804119797843668992.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804125377400553474.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804126764347850752.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804129657113165824.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804130996236992514.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804130998971678723.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804132940250759168.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804133415494750209.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804133521023324160.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804133675663261696.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804142982064668673.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804145685264220166.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804150024875732992.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804154414986563584.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804158926937792512.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804161132323803136.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804176989817077760.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804180749326880768.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804182756116856832.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804194229140488192.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804203375298539520.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804211176288686080.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804240867972304896.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804243640298119168.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804264778608902144.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804272163838722048.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804273179334209536.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804281537579614209.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804281566667173892.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804282150241652737.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804287640438734848.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804289444039847936.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804302532738744320.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804304042423971841.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804309989749878785.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804319197232824320.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804325547723620352.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804330092725993473.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804330492124364800.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804331391001432064.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804331394105221125.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804339891630993408.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804341450968276992.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804345061148332036.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804347259047542784.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804356723351945216.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804356729022676992.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804356739701346304.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804356796341227520.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804357874126307328.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804358145351024640.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804358999466504193.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804359432016723968.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804364766764417024.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804364908792074240.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804370071044968450.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804370194026086400.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804374585131016192.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804379537232564224.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804393377919803392.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804396146646978560.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804396360405569537.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804396363668668416.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804399694935969793.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804399751965921281.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804404877103247360.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804406739953127428.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804414970406518784.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804420519227334656.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804420528161202176.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804422368454123520.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804424864404602880.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804429231149219840.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804429269304741889.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804429272056287232.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804437939778363392.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804439549757816832.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804439552710557702.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804442562115280896.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804443013443362816.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804444655937011713.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804450218670313473.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804452772036775936.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804454606008885248.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804455668702990337.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804456043107340288.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804456064036917248.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804456089227960320.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804456168919736321.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804471642042880001.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804475247357476864.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804477830922956800.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804480216856924161.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804482142696828928.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804482158240956416.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804482167350890497.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804482180076503044.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804483495171014656.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804486525392130048.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804495551370694656.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804498611564380160.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804501165031440385.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804502771030433794.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804504952244727810.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804508148920782848.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804515125550055424.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804517080661983232.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804527283780382721.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804533890853408768.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804537473879732224.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804543364242796544.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804551839790178304.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804556904668266497.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804563623305682944.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804592928417021952.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804595965919232000.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804603765252722688.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804630176848117761.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804639248452186113.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804646992588709888.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804662311147438080.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804662313466859520.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804670913702744064.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804676988925607937.png
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804677761474379776.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804678993521819648.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804680687643197440.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804696220929327104.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804710466480177152.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804711476657201153.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804712569143521280.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804712575271366656.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804712729412038656.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804716766295425028.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804717019966873605.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804725089757528064.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804736199726350336.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804739480792006656.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804739587113451520.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804739587117563904.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804739587117617152.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804739587117633536.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804743433831256064.jpg
c:\Users\KIIT\clickbait-credibility-system\data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804752021941288960.jpg

In [5]:
import pandas as pd

clickbait_path = project_root / "data" / "processed" / "clickbait.csv"

df = pd.read_csv(clickbait_path)

print("Shape:", df.shape)

print("\nColumns:")
print(df.columns.tolist())

print("\nMissing values:")
print(df.isna().sum())

print("\nFirst 5 rows:")
display(df.head())

Shape: (19538, 4)

Columns:
['id', 'headline', 'clickbait_score', 'clickbait_label']

Missing values:
id                 0
headline           0
clickbait_score    0
clickbait_label    0
dtype: int64

First 5 rows:

,id,headline,clickbait_score,clickbait_label
0,858464162594172928,Facts That Will Be Truly Upsetting To '90s Girls,1.000000,clickbait
1,858462320779026433,‘Inexcusable’ failures in UK’s response to mod...,0.133333,no-clickbait
2,858460992073863168,Inside Kim Jong-un's camps of death: Former No...,0.400000,no-clickbait
3,858459539296980995,Trump Has Flip-Flopped. But His Supporters Are...,0.266667,no-clickbait
4,858455355948384257,Donald Trump said being US president was harde...,0.000000,no-clickbait

In [6]:
print("Class distribution:")
print(df["clickbait_label"].value_counts())

print("\nClass proportions:")
print(df["clickbait_label"].value_counts(normalize=True))

Class distribution:
clickbait_label
no-clickbait    14777
clickbait        4761
Name: count, dtype: int64

Class proportions:
clickbait_label
no-clickbait    0.756321
clickbait       0.243679
Name: proportion, dtype: float64

In [7]:
print("Shape:", df.shape)

print("\nColumns:")
for column in df.columns:
    print("-", column)

print("\nFirst 5 rows:")
display(df.head())

print("\nData types:")
print(df.dtypes)

Shape: (19538, 4)

Columns:
- id
- headline
- clickbait_score
- clickbait_label

First 5 rows:

,id,headline,clickbait_score,clickbait_label
0,858464162594172928,Facts That Will Be Truly Upsetting To '90s Girls,1.000000,clickbait
1,858462320779026433,‘Inexcusable’ failures in UK’s response to mod...,0.133333,no-clickbait
2,858460992073863168,Inside Kim Jong-un's camps of death: Former No...,0.400000,no-clickbait
3,858459539296980995,Trump Has Flip-Flopped. But His Supporters Are...,0.266667,no-clickbait
4,858455355948384257,Donald Trump said being US president was harde...,0.000000,no-clickbait

Data types:
id                   int64
headline               str
clickbait_score    float64
clickbait_label        str
dtype: object

In [8]:
print("Missing values:")
print(df.isna().sum())

print("\nDuplicate complete rows:")
print(df.duplicated().sum())

if "id" in df.columns:
    print("\nDuplicate IDs:")
    print(df["id"].duplicated().sum())

Missing values:
id                 0
headline           0
clickbait_score    0
clickbait_label    0
dtype: int64

Duplicate complete rows:
0

Duplicate IDs:
0

In [9]:
print("Headline column check:")

if "headline" in df.columns:
    print("Missing headlines:", df["headline"].isna().sum())
    print(
        "Empty headlines:",
        df["headline"].fillna("").str.strip().eq("").sum()
    )
    print("\nHeadline length:")
    print(df["headline"].fillna("").str.len().describe())
else:
    print("ERROR: 'headline' column does not exist.")

Headline column check:
Missing headlines: 0
Empty headlines: 0

Headline length:
count    19538.000000
mean        70.462279
std         33.083553
min          5.000000
25%         56.000000
50%         67.000000
75%         80.000000
max       1340.000000
Name: headline, dtype: float64

In [10]:
print("Raw Clickbait-17 files:")

clickbait_raw = project_root / "data" / "raw" / "clickbait"

for path in clickbait_raw.rglob("*"):
    if path.is_file():
        print(path.relative_to(project_root))

Raw Clickbait-17 files:
data\raw\clickbait\clickbait17-train-170630.zip
data\raw\clickbait\train\clickbait17-validation-170630\instances.jsonl
data\raw\clickbait\train\clickbait17-validation-170630\truth.jsonl
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804083561460428801.png
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804088734731812865.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804119509338640385.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804119797843668992.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804125377400553474.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804126764347850752.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804129657113165824.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804130996236992514.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804130998971678723.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804132940250759168.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804133415494750209.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804133521023324160.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804133675663261696.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804142982064668673.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804145685264220166.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804150024875732992.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804154414986563584.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804158926937792512.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804161132323803136.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804176989817077760.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804180749326880768.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804182756116856832.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804194229140488192.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804203375298539520.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804211176288686080.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804240867972304896.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804243640298119168.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804264778608902144.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804272163838722048.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804273179334209536.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804281537579614209.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804281566667173892.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804282150241652737.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804287640438734848.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804289444039847936.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804302532738744320.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804304042423971841.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804309989749878785.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804319197232824320.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804325547723620352.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804330092725993473.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804330492124364800.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804331391001432064.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804331394105221125.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804339891630993408.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804341450968276992.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804345061148332036.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804347259047542784.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804356723351945216.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804356729022676992.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804356739701346304.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804356796341227520.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804357874126307328.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804358145351024640.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804358999466504193.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804359432016723968.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804364766764417024.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804364908792074240.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804370071044968450.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804370194026086400.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804374585131016192.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804379537232564224.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804393377919803392.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804396146646978560.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804396360405569537.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804396363668668416.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804399694935969793.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804399751965921281.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804404877103247360.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804406739953127428.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804414970406518784.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804420519227334656.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804420528161202176.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804422368454123520.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804424864404602880.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804429231149219840.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804429269304741889.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804429272056287232.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804437939778363392.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804439549757816832.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804439552710557702.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804442562115280896.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804443013443362816.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804444655937011713.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804450218670313473.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804452772036775936.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804454606008885248.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804455668702990337.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804456043107340288.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804456064036917248.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804456089227960320.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804456168919736321.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804471642042880001.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804475247357476864.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804477830922956800.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804480216856924161.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804482142696828928.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804482158240956416.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804482167350890497.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804482180076503044.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804483495171014656.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804486525392130048.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804495551370694656.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804498611564380160.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804501165031440385.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804502771030433794.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804504952244727810.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804508148920782848.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804515125550055424.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804517080661983232.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804527283780382721.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804533890853408768.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804537473879732224.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804543364242796544.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804551839790178304.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804556904668266497.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804563623305682944.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804592928417021952.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804595965919232000.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804603765252722688.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804630176848117761.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804639248452186113.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804646992588709888.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804662311147438080.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804662313466859520.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804670913702744064.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804676988925607937.png
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804677761474379776.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804678993521819648.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804680687643197440.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804696220929327104.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804710466480177152.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804711476657201153.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804712569143521280.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804712575271366656.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804712729412038656.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804716766295425028.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804717019966873605.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804725089757528064.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804736199726350336.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804739480792006656.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804739587113451520.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804739587117563904.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804739587117617152.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804739587117633536.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804743433831256064.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804752021941288960.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804755698986807296.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804756215435644928.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804763305210318848.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804766131227688960.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804767137579446272.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804772146601922560.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804777246548520962.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804777664003313664.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804778522464153600.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804787478569717760.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804798028955545600.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804798028959784960.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804799059525562369.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804802268700626944.png
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804803596319604736.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804814814987980800.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804815157234835456.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804817878650384384.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804818563420848128.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804818932653760512.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804818933282983936.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804819902880223233.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804822179917479936.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804822334804791296.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804827516947103744.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804833281116143616.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804835244071354368.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804836213161005057.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804843354622136320.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804849534706728960.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804849559230816256.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804849597147295744.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804849617984573441.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804850137088585728.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804852662852321281.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804857251420717057.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804859639007281152.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804862721283932165.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804863403873488896.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804868003963764737.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804872157926785025.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804879853073956864.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804880712822358016.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804880716290998272.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804882911044440069.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804889409338351616.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804918978158149632.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804920601601277952.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804937953424318465.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804941841623896064.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804954592345780224.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804975139695763457.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_804981633195667456.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_805008755322683392.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_805011644711661568.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_805028428990717953.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_805036325300736000.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_805053509544607744.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_805059265459273729.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_805069335479795714.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_805072128471142400.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_805079152487301120.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_805086951774654464.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_805087954913796096.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_805092244948717568.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_805102351333945344.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_805103666269220864.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_805103668773158912.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_805108863481606144.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_805109557144027136.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_805113694757584896.jpg
data\raw\clickbait\train\clickbait17-validation-170630\media\photo_805119446016815104.jpg

In [11]:
longest = (
    df.assign(headline_length=df["headline"].str.len())
      .sort_values("headline_length", ascending=False)
      [["id", "headline", "headline_length", "clickbait_score", "clickbait_label"]]
      .head(10)
)

display(longest)

,id,headline,headline_length,clickbait_score,clickbait_label
15917,814316266089549824,Random acts of kindness from 2016 that will wa...,1340,0.666667,clickbait
17033,811068618490413056,Random acts of kindness from 2016 that will wa...,1340,0.800000,clickbait
14585,818052636142354436,25 things you still don't know about Barack Ob...,1297,0.533333,clickbait
6897,839550191132778496,12 Perspectives On The Women’s Strike You Need...,1255,0.800000,clickbait
15806,814663554313945088,29 heartwarming photos of foster kids getting ...,1155,0.666667,clickbait
11748,826029700971651072,SAG Awards 2017 highlights Ashton Kutcher Asht...,1016,0.600000,clickbait
11018,828090784633200643,Throwback photos of politicians that will make...,820,0.800000,clickbait
11002,828166276338032640,"The most polluted cities in the world, ranked ...",693,0.866667,clickbait
9530,832352615413460992,A crash course on Steve Bannon Who is Stephen ...,645,0.133333,no-clickbait
9741,831767506457128962,19 celebrities you didn't know were twins Cele...,554,1.000000,clickbait

In [12]:
for _, row in longest.iterrows():
    print("=" * 100)
    print("ID:", row["id"])
    print("Length:", row["headline_length"])
    print("Score:", row["clickbait_score"])
    print("Label:", row["clickbait_label"])
    print("Headline:")
    print(row["headline"])

====================================================================================================
ID: 814316266089549824
Length: 1340
Score: 0.66666666662
Label: clickbait
Headline:
Random acts of kindness from 2016 that will warm your heart When this stranger paid for a teacher's school supplies at Walmart These employees who paused to pray with a grieving widow This cop who stopped a barefoot homeless woman, and bought her shoes This waiter who helped feed a man without hands When a chance meeting brought this grieving widower joy This feisty 6-year-old who defended her autistic brother When FSU player Travis Rudolph sat with a boy who was eating lunch alone When these football players supported a cheerleader who was recently diagnosed with cancer The reason why this little boy asked his mom to pack 2 school lunches When coworkers helped this teacher cross an item off her bucket list When this little boy gave police officers "free hugs" after violent protests When a restaurant surprised a woman with this sweet note When Jon Voight bought 6 turkeys for this woman over Thanksgiving This barber who spends his day off giving haircuts to the homeless When this grandma invited a random teen to Thanksgiving dinner This bus driver who bought hats and gloves for kids in need on his route This teen who returned to work after a car accident to help the homeless When this flight attendant calmed a stressed mom's antsy baby on a plane These strangers who came together to give a dying dog one last special day
====================================================================================================
ID: 811068618490413056
Length: 1340
Score: 0.7999999999599999
Label: clickbait
Headline:
Random acts of kindness from 2016 that will warm your heart When this stranger paid for a teacher's school supplies at Walmart These employees who paused to pray with a grieving widow This cop who stopped a barefoot homeless woman, and bought her shoes This waiter who helped feed a man without hands When a chance meeting brought this grieving widower joy This feisty 6-year-old who defended her autistic brother When FSU player Travis Rudolph sat with a boy who was eating lunch alone When these football players supported a cheerleader who was recently diagnosed with cancer The reason why this little boy asked his mom to pack 2 school lunches When coworkers helped this teacher cross an item off her bucket list When this little boy gave police officers "free hugs" after violent protests When a restaurant surprised a woman with this sweet note When Jon Voight bought 6 turkeys for this woman over Thanksgiving This barber who spends his day off giving haircuts to the homeless When this grandma invited a random teen to Thanksgiving dinner This bus driver who bought hats and gloves for kids in need on his route This teen who returned to work after a car accident to help the homeless When this flight attendant calmed a stressed mom's antsy baby on a plane These strangers who came together to give a dying dog one last special day
====================================================================================================
ID: 818052636142354436
Length: 1297
Score: 0.5333333333
Label: clickbait
Headline:
25 things you still don't know about Barack Obama How well do you know No. 44? He's left-handed. He's quite capable of being his own anger translator. He eats (but does not ration) almonds. He's a binge-watcher. He's a big iPad guy. He's a prospective Chevy Volt owner. He's the 11th president to be raised without a father. He's "pretty terrible" at March Madness brackets. His favorite song of 2015 was Kendrick Lamar's "How Much a Dollar Cost." He read Harry Potter books with his eldest daughter. He's probably the biggest "Star Trek" fan in White House history. He's got more Grammys than Tupac, Biggie and The Who combined. He saw "Hamilton" in previews. As of his 55th birthday, his net worth was a reported $12.2 million. His favorite movies are "The Godfather" and "The Godfather: Part II." He reveres the original GOP standard-bearer. He signed up for an Obamacare plan. He's practically Mike Pence's next-door neighbor. His favorite place to hang in the White House is the Truman Balcony. His all-time favorite all-American invention is the lightbulb. He's a II, as in "Jaws II." His family's No. 1 charity serves vets and their families. He is a Christian who was born in the United States. His old apartment in Pasadena, Calif., is something of a landmark. He writes a lot of letters.
====================================================================================================
ID: 839550191132778496
Length: 1255
Score: 0.7999999999599999
Label: clickbait
Headline:
12 Perspectives On The Women’s Strike You Need To Read 1. “Women of America: we’re going on strike,” by the organizers of the strike in The Guardian 2. “While the Iron is Hot: The case for the Women’s Strike,” by Dayna Tortorici in n+1 3. “Striking On International Women’s Day Is Not a Privilege,” by Magally A. Miranda Alcazar and Kate D. Griffiths in The Nation 4. “#DayWithoutAWoman: For Domestic and Low-Wage Workers, the Stakes Are Higher Than Ever,” by Ai-jen Poo in Glamour 5. “Remaining Open: On Women, Capital and Care,” by Meredith Graves at MTV News 6. “The Only Way to Know If Striking Works Is to Do It,” by Dayna Evans at The Cut 7. “Argentina’s Life-or-Death Women’s Movement,” by Verónica Gago & Agustina Santomaso in Jacobin 8. “International Women’s Day Has Been Stripped Of Its Radical Roots. That’s About To Change,” by Katie McDonough at Fusion 9. “Here’s How Women’s Web Sites Will Cover the Strike,” by Kara Bloomgarden-Smoke in Women’s Wear Daily 10. “The Women’s Strike and the Messy Space of Change” by Jia Tolentino at The New Yorker 11. “A Day Without a Woman” by the organizers of the Women’s March 12. “Thirteen Mildly Righteous Out-of-Office Replies To Use While You’re At The Women’s Strike” by Heather Dockray at Mashable
====================================================================================================
ID: 814663554313945088
Length: 1155
Score: 0.66666666664
Label: clickbait
Headline:
29 heartwarming photos of foster kids getting adopted Foster kids at the moment of adoption Foster kids at the moment of adoption Foster kids at the moment of adoption Foster kids at the moment of adoption Foster kids at the moment of adoption Foster kids at the moment of adoption Foster kids at the moment of adoption Foster kids at the moment of adoption Foster kids at the moment of adoption Foster kids at the moment of adoption Foster kids at the moment of adoption Foster kids at the moment of adoption Foster kids at the moment of adoption Foster kids at the moment of adoption Foster kids at the moment of adoption Foster kids at the moment of adoption Foster kids at the moment of adoption Foster kids at the moment of adoption Foster kids at the moment of adoption Foster kids at the moment of adoption Foster kids at the moment of adoption Foster kids at the moment of adoption Foster kids at the moment of adoption Foster kids at the moment of adoption Foster kids at the moment of adoption Foster kids at the moment of adoption Foster kids at the moment of adoption Foster kids at the moment of adoption Foster kids at the moment of adoption
====================================================================================================
ID: 826029700971651072
Length: 1016
Score: 0.59999999998
Label: clickbait
Headline:
SAG Awards 2017 highlights Ashton Kutcher Ashton Kutcher Julia Louis-Dreyfus Julia Louis-Dreyfus Gina Rodriguez and John Legend Best Male Actor in a Comedy Series William H. Macy Taraji P. Henson and Octavia Spencer Best Ensemble in a Comedy Series John Krasinski Viola Davis Viola Davis Kate Hudson Best Supporting Actor Lucas Hedges and Casey Affleck Michelle Dockery and James Marsden Best Female Actor in a Miniseries or TV Movie Salma Hayek Best Male Actor in a Miniseries or TV Movie Bryan Cranston Dolly Parton Lily Tomlin Gabrielle Carteris Viggo Mortensen and Kathryn Hahn Best Male Actor in a Drama Series Steven Yeun and Alia Shawkat Best Female Actor in a Drama Series Mahershala Ali and Naomie Harris Riz Ahmed and Rashida Jones Best Ensemble in a Drama Series Jonah Hill Jonah Hill and Emma Stone Best Female Actor in a Leading Role Viola Davis and Denzel Washington Alex Greenwald and Brie Larson Brie Larson Best Male Actor in a Leading Role Jeffrey Tambor Nicole Kidman Best Cast in a Motion Picture
====================================================================================================
ID: 828090784633200643
Length: 820
Score: 0.8
Label: clickbait
Headline:
Throwback photos of politicians that will make you do a double-take Guess the names of these famous U.S. politicians Guess who? Sen. Bernie Sanders Guess who? Vide President Joe Biden Guess who? House Minority Leader Nancy Pelosi Guess who? Sen. Tim Kaine Guess who? Rep. John Lewis Guess who? Sen. Elizabeth Warren Guess who? Former President George W. Bush and his wife Laura Guess who? President-elect Donald Trump Guess who? Former GOP vice-presidential nominee Sarah Palin and her husband Todd Guess who? President Barack Obama and first lady Michelle Obama Guess who? Sen. John McCain Guess who? Former President Bill Clinton and Hillary Clinton Guess who? Gov. Chris Christie Guess who? Former House Speaker Newt Gingrich Guess who? Minority Leader Harry Reid Guess who? Former Secretary of State Condoleezza Rice
====================================================================================================
ID: 828166276338032640
Length: 693
Score: 0.86666666666
Label: clickbait
Headline:
The most polluted cities in the world, ranked The most polluted air on the planet 30. Jodhpur, India 29. Tangshan, China 28. Kampala, Uganda 27. Agra, India 26. Bushehr, Iran 25. Narayangong, Bangladesh 24. Hengshui, China 23. Rawalpindi, Pakistan 22. Mandi Gobindgarh, India 21. Amritsar, India 20. Peshawar, Pakistan 19. Handan, China 18. Lucknow, India 17. Firozabad, India 16. Khanna, India 15. Kanpur, India 14. Shijiazhuang, China 13. Dammam, Saudi Arabia 12. Ludhiana, India 11. Delhi, India 10. Baoding, China 9. Xingtai, China 8. Bamenda, Cameroon 7. Raipur, India 6. Patna, India 5. Al Jubail, Saudi Arabia 4. Riyadh, Saudi Arabia 3. Allahabad, India 2. Gwalior, India 1. Zabol, Iran
====================================================================================================
ID: 832352615413460992
Length: 645
Score: 0.13333333332
Label: no-clickbait
Headline:
A crash course on Steve Bannon Who is Stephen K. Bannon? He’s President Trump’s right-hand man Trump has since given him more power He was chairman of Breitbart News His Breitbart roots caused an uproar He told the media to “keep its mouth shut” He was an investment banker He made big money off of “Seinfeld” He oversaw an artificial world He was involved in an abuse lawsuit He's been married three times He helped write the travel ban He was raised among Democrats He served in the Navy He’s not fond of women’s lib He's been a producer on 18 films He made a bad deal with an internet gaming company He has degrees from Harvard and Georgetown
====================================================================================================
ID: 831767506457128962
Length: 554
Score: 1.0
Label: clickbait
Headline:
19 celebrities you didn't know were twins Celebrity twins you had no idea existed Gisele and Patrícia Bündchen Ashton and Michael Kutcher Scarlett and Hunter Johansson Jon and Dan Heder Jenna Bush Hager and Barbara Bush Aaron and Angel Carter Vin and Paul Diesel Tasha and Sidra Smith Rami and Sami Malek Alanis and Wade Morissette Dylan and Cole Sprouse Willow and Autumn Shields Judy and Joselin Reyes Shawn and Aaron Ashmore Charles and Max Carver Giovanni and Marissa Ribisi Kate and Karen Lawler Samantha and Charlotte Ronson Elvis and Jesse Presley